# Matrix Selection and Indexing

example.matrix[rows,columns]

In [1]:
mat <- matrix(1:50,byrow=TRUE,nrow=5)

In [2]:
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40   
[5,] 41   42   43   44   45   46   47   48   49   50

In [3]:
# Grab first row
mat[1,]

[1]  1  2  3  4  5  6  7  8  9 10

In [4]:
#Grab first column
mat[,1]

[1]  1 11 21 31 41

In [5]:
# Grab first 3 rows
mat[1:3,]

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30

In [6]:
# Grab top left rectangle of:
# 1,2,3
# 11,12,13
#
mat[1:2,1:3]

[,1] [,2] [,3]
[1,]  1    2    3  
[2,] 11   12   13

In [7]:
# Grab last two columns
mat[,9:10]


[,1] [,2]
[1,]  9   10  
[2,] 19   20  
[3,] 29   30  
[4,] 39   40  
[5,] 49   50

In [8]:
# Grab a center square of:
# 15,16
# 25,26
mat[2:3,5:6]

[,1] [,2]
[1,] 15   16  
[2,] 25   26