# Creating a Matrix

In [1]:
# we should show a quick tip for quickly creating sequential numeric vectors, you can use the colon notation from slicing to create sequential vectors:
1:10

[1]  1  2  3  4  5  6  7  8  9 10

In [2]:
v <- 1:10
v

[1]  1  2  3  4  5  6  7  8  9 10

In [3]:
#  use the matrix() function. We can pass in a vector into the matrix:
matrix(v)

[,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10

Here we have a two-dimensional matrix which is 10 rows by 1 column. Now what if we want to specify the number of rows? We can pass the parameter/argument into the matrix function called nrow which stands for number of rows:

In [4]:
matrix(v,nrow=2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

Now we have a 2 by 5 matrix. Notice that the nrow argument allows this to happen. But how do we decide the fill order? We could have filed columns first (as we did above) or filled out the rows first insequential order. The byrow argument allows you to specify whether or not you want to fill out the matrix by rows or by columns. For example:

In [5]:
matrix(1:12,byrow = FALSE,nrow=4)

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [6]:
matrix(1:12, byrow=TRUE, nrow=4)

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [7]:
v

[1]  1  2  3  4  5  6  7  8  9 10

## Creating Matrices from Vectors

In [8]:
# We can combine vectors to later input them into a matrix. For example imagine the following vectors below of stock prices:
# not real prices
goog <- c(450,451,452,445,468)
msft <- c(230,231,232,236,228)

In [9]:
stocks <- c(goog,msft)

In [10]:
stock.matrix <- matrix(stocks,byrow=TRUE,nrow=2)

In [11]:
stock.matrix

[,1] [,2] [,3] [,4] [,5]
[1,] 450  451  452  445  468 
[2,] 230  231  232  236  228

## Naming Matrices