## Matrix Arithmetic

In [1]:
mat <- matrix(1:50,byrow=TRUE,nrow=5)
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40   
[5,] 41   42   43   44   45   46   47   48   49   50

In [2]:
# Multiplication
2*mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  2    4    6    8   10   12   14   16   18    20  
[2,] 22   24   26   28   30   32   34   36   38    40  
[3,] 42   44   46   48   50   52   54   56   58    60  
[4,] 62   64   66   68   70   72   74   76   78    80  
[5,] 82   84   86   88   90   92   94   96   98   100

In [3]:
# Division (reciprocal)
1/mat

[,1]       [,2]       [,3]       [,4]       [,5]       [,6]      
[1,] 1.00000000 0.50000000 0.33333333 0.25000000 0.20000000 0.16666667
[2,] 0.09090909 0.08333333 0.07692308 0.07142857 0.06666667 0.06250000
[3,] 0.04761905 0.04545455 0.04347826 0.04166667 0.04000000 0.03846154
[4,] 0.03225806 0.03125000 0.03030303 0.02941176 0.02857143 0.02777778
[5,] 0.02439024 0.02380952 0.02325581 0.02272727 0.02222222 0.02173913
     [,7]       [,8]       [,9]       [,10]     
[1,] 0.14285714 0.12500000 0.11111111 0.10000000
[2,] 0.05882353 0.05555556 0.05263158 0.05000000
[3,] 0.03703704 0.03571429 0.03448276 0.03333333
[4,] 0.02702703 0.02631579 0.02564103 0.02500000
[5,] 0.02127660 0.02083333 0.02040816 0.02000000

In [4]:
# Division
mat/2

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  0.5  1    1.5  2    2.5  3    3.5  4    4.5  5   
[2,]  5.5  6    6.5  7    7.5  8    8.5  9    9.5 10   
[3,] 10.5 11   11.5 12   12.5 13   13.5 14   14.5 15   
[4,] 15.5 16   16.5 17   17.5 18   18.5 19   19.5 20   
[5,] 20.5 21   21.5 22   22.5 23   23.5 24   24.5 25

In [5]:
# Power
mat ^ 2

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    4    9   16   25   36   49   64   81  100 
[2,]  121  144  169  196  225  256  289  324  361  400 
[3,]  441  484  529  576  625  676  729  784  841  900 
[4,]  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 
[5,] 1681 1764 1849 1936 2025 2116 2209 2304 2401 2500

## Comparison operators with matrices

In [6]:
mat > 17

[,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9]  [,10]
[1,] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE
[3,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[4,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[5,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

In [7]:
# Matrix Arithmetic with multiple matrices
# We can use multiple matrices with arithmetic as well, for example:
mat + mat


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  2    4    6    8   10   12   14   16   18    20  
[2,] 22   24   26   28   30   32   34   36   38    40  
[3,] 42   44   46   48   50   52   54   56   58    60  
[4,] 62   64   66   68   70   72   74   76   78    80  
[5,] 82   84   86   88   90   92   94   96   98   100

In [8]:
mat / mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1    1    1    1    1    1    1    1    1    1    
[2,] 1    1    1    1    1    1    1    1    1    1    
[3,] 1    1    1    1    1    1    1    1    1    1    
[4,] 1    1    1    1    1    1    1    1    1    1    
[5,] 1    1    1    1    1    1    1    1    1    1

In [9]:
mat ^ mat


[,1]         [,2]         [,3]         [,4]         [,5]        
[1,] 1.000000e+00 4.000000e+00 2.700000e+01 2.560000e+02 3.125000e+03
[2,] 2.853117e+11 8.916100e+12 3.028751e+14 1.111201e+16 4.378939e+17
[3,] 5.842587e+27 3.414279e+29 2.088047e+31 1.333736e+33 8.881784e+34
[4,] 1.706917e+46 1.461502e+48 1.291100e+50 1.175664e+52 1.102507e+54
[5,] 1.330878e+66 1.501309e+68 1.734377e+70 2.050774e+72 2.480636e+74
     [,6]         [,7]         [,8]         [,9]         [,10]       
[1,] 4.665600e+04 8.235430e+05 1.677722e+07 3.874205e+08 1.000000e+10
[2,] 1.844674e+19 8.272403e+20 3.934641e+22 1.978420e+24 1.048576e+26
[3,] 6.156120e+36 4.434265e+38 3.314552e+40 2.567686e+42 2.058911e+44
[4,] 1.063874e+56 1.055513e+58 1.075912e+60 1.125951e+62 1.208926e+64
[5,] 3.068035e+76 3.877924e+78 5.007021e+80 6.600972e+82 8.881784e+84

## Matrix multiplication

A quick side note on matrix multiplications. You can perform arithmetic multiplication on an element by element basis using the * sign in R. You should note this is not the same as Matrix Multiplication. If you are familiar with the mathematics behind this topic and want to use R to perform true matrix multiplication, you can use the following:

In [11]:
mat2 <- matrix(1:9, nrow=3)
mat2

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [12]:
# True Matrix Multiplication
mat2 %*% mat2

[,1] [,2] [,3]
[1,] 30   66   102 
[2,] 36   81   126 
[3,] 42   96   150